/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    configurations: Configuration;
    customers: Customer;
    orders: Order;
    expenses: Expense;
    products: Product;
    warehouses: Warehouse;
    suppliers: Supplier;
    'stock-transactions': StockTransaction;
    'production-runs': ProductionRun;
    'job-cards': JobCard;
    deliveries: Delivery;
    'purchase-orders': PurchaseOrder;
    payments: Payment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    configurations: ConfigurationsSelect<false> | ConfigurationsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'stock-transactions': StockTransactionsSelect<false> | StockTransactionsSelect<true>;
    'production-runs': ProductionRunsSelect<false> | ProductionRunsSelect<true>;
    'job-cards': JobCardsSelect<false> | JobCardsSelect<true>;
    deliveries: DeliveriesSelect<false> | DeliveriesSelect<true>;
    'purchase-orders': PurchaseOrdersSelect<false> | PurchaseOrdersSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Display name for the user
   */
  name?: string | null;
  roles: ('admin' | 'owner' | 'staff')[];
  tenant?: (string | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  slug: string;
  logo?: (string | null) | Media;
  colorTheme?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configurations".
 */
export interface Configuration {
  id: string;
  tenant: string | Tenant;
  invoiceText?: string | null;
  measurementUnits?:
    | {
        unit: string;
        id?: string | null;
      }[]
    | null;
  productCategories?:
    | {
        category: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Define custom fields for orders (e.g., [{"name": "woodType", "label": "Wood Type", "type": "text"}])
   */
  customOrderFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone: string;
  email?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders with payment tracking and production status
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  customer: string | Customer;
  type: 'ready-made' | 'custom';
  orderDate: string;
  deliveryDate?: string | null;
  /**
   * Amount in PKR
   */
  totalAmount: number;
  /**
   * Amount in PKR
   */
  advancePaid?: number | null;
  /**
   * Amount in PKR
   */
  remainingPaid?: number | null;
  dueAmount?: number | null;
  status: 'pending' | 'in_progress' | 'delivered';
  items: {
    product: string | Product;
    /**
     * SKU or Name of the selected variant
     */
    variant?: string | null;
    quantity: number;
    /**
     * Amount in PKR
     */
    price: number;
    customizations?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    productionStatus?: ('pending' | 'in_production' | 'ready' | 'delivered') | null;
    id?: string | null;
  }[];
  paymentStatus?: ('unpaid' | 'partial' | 'paid') | null;
  /**
   * Stores dynamic fields defined in configuration
   */
  customFieldsData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product catalog with inventory tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Auto-generated from name
   */
  slug?: string | null;
  /**
   * Stock Keeping Unit - unique identifier
   */
  sku?: string | null;
  type: 'finished_good' | 'raw_material' | 'service';
  price?: number | null;
  cost?: number | null;
  /**
   * e.g., pcs, feet, kg, meters
   */
  unit?: string | null;
  /**
   * Auto-calculated sum of all warehouses
   */
  stock?: number | null;
  /**
   * Managed via stock transactions
   */
  warehouseStock?:
    | {
        warehouse: string | Warehouse;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Product variations (size, color, etc.)
   */
  variants?:
    | {
        name: string;
        sku?: string | null;
        price?: number | null;
        stock?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw materials required to manufacture this product
   */
  bom?:
    | {
        material: string | Product;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: string;
  name: string;
  address?: string | null;
  /**
   * If true, this will be the default warehouse for new orders/products.
   */
  isDefault?: boolean | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: string;
  title: string;
  amount: number;
  date: string;
  description?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  name: string;
  contactPerson?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  paymentTerms?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-transactions".
 */
export interface StockTransaction {
  id: string;
  date: string;
  type: 'purchase_receive' | 'order_deduction' | 'manual_adjust' | 'return' | 'waste';
  product: string | Product;
  warehouse: string | Warehouse;
  /**
   * Positive for adding stock, negative for removing.
   */
  quantity: number;
  reference?: string | null;
  supplier?: (string | null) | Supplier;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-runs".
 */
export interface ProductionRun {
  id: string;
  order: string | Order;
  orderItem: string;
  product: string | Product;
  status: 'planned' | 'in_progress' | 'quality_check' | 'completed';
  stages?:
    | {
        stage: 'cutting' | 'assembly' | 'sanding' | 'upholstery' | 'qc';
        status?: ('pending' | 'in_progress' | 'completed') | null;
        completedAt?: string | null;
        assignedTo?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-cards".
 */
export interface JobCard {
  id: string;
  productionRun: string | ProductionRun;
  stage: string;
  worker: string | User;
  status?: ('assigned' | 'in_progress' | 'done') | null;
  notes?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries".
 */
export interface Delivery {
  id: string;
  order: string | Order;
  status: 'pending' | 'in_transit' | 'delivered' | 'failed';
  scheduledDate?: string | null;
  driver?: (string | null) | User;
  proofOfDelivery?: (string | null) | Media;
  notes?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders".
 */
export interface PurchaseOrder {
  id: string;
  supplier: string | Supplier;
  status: 'draft' | 'ordered' | 'received' | 'cancelled';
  items: {
    product: string | Product;
    quantity: number;
    unitCost?: number | null;
    id?: string | null;
  }[];
  totalCost?: number | null;
  expectedDeliveryDate?: string | null;
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  order: string | Order;
  amount: number;
  method: 'cash' | 'jazzcash' | 'easypaisa' | 'bank_transfer';
  /**
   * Transaction ID or Receipt No.
   */
  reference?: string | null;
  date: string;
  status: 'pending' | 'completed' | 'failed';
  tenant: string | Tenant;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'configurations';
        value: string | Configuration;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'expenses';
        value: string | Expense;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: string | Warehouse;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'stock-transactions';
        value: string | StockTransaction;
      } | null)
    | ({
        relationTo: 'production-runs';
        value: string | ProductionRun;
      } | null)
    | ({
        relationTo: 'job-cards';
        value: string | JobCard;
      } | null)
    | ({
        relationTo: 'deliveries';
        value: string | Delivery;
      } | null)
    | ({
        relationTo: 'purchase-orders';
        value: string | PurchaseOrder;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  colorTheme?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configurations_select".
 */
export interface ConfigurationsSelect<T extends boolean = true> {
  tenant?: T;
  invoiceText?: T;
  measurementUnits?:
    | T
    | {
        unit?: T;
        id?: T;
      };
  productCategories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  customOrderFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  type?: T;
  orderDate?: T;
  deliveryDate?: T;
  totalAmount?: T;
  advancePaid?: T;
  remainingPaid?: T;
  dueAmount?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        price?: T;
        customizations?: T;
        productionStatus?: T;
        id?: T;
      };
  paymentStatus?: T;
  customFieldsData?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  title?: T;
  amount?: T;
  date?: T;
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  type?: T;
  price?: T;
  cost?: T;
  unit?: T;
  stock?: T;
  warehouseStock?:
    | T
    | {
        warehouse?: T;
        quantity?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        price?: T;
        stock?: T;
        id?: T;
      };
  bom?:
    | T
    | {
        material?: T;
        quantity?: T;
        id?: T;
      };
  description?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  isDefault?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  contactPerson?: T;
  phone?: T;
  email?: T;
  address?: T;
  paymentTerms?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-transactions_select".
 */
export interface StockTransactionsSelect<T extends boolean = true> {
  date?: T;
  type?: T;
  product?: T;
  warehouse?: T;
  quantity?: T;
  reference?: T;
  supplier?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-runs_select".
 */
export interface ProductionRunsSelect<T extends boolean = true> {
  order?: T;
  orderItem?: T;
  product?: T;
  status?: T;
  stages?:
    | T
    | {
        stage?: T;
        status?: T;
        completedAt?: T;
        assignedTo?: T;
        id?: T;
      };
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-cards_select".
 */
export interface JobCardsSelect<T extends boolean = true> {
  productionRun?: T;
  stage?: T;
  worker?: T;
  status?: T;
  notes?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveries_select".
 */
export interface DeliveriesSelect<T extends boolean = true> {
  order?: T;
  status?: T;
  scheduledDate?: T;
  driver?: T;
  proofOfDelivery?: T;
  notes?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders_select".
 */
export interface PurchaseOrdersSelect<T extends boolean = true> {
  supplier?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitCost?: T;
        id?: T;
      };
  totalCost?: T;
  expectedDeliveryDate?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  order?: T;
  amount?: T;
  method?: T;
  reference?: T;
  date?: T;
  status?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}